# --------- TLS configuration ----------
# Minimum TLS v1.2 with strong cyphers

[tls.options.default]
   minVersion = "VersionTLS12"
   cipherSuites = [
     "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
     "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
     "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
     "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
     "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
     "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
   ]

# To use minimum TLS v1.1 to support Windows 7 and other old clients uncomment the lines below
# and delete other configuration

# [tls.options.default]
#   minVersion = "VersionTLS11"

#-------------- HTTPS redirect -------------

[http.middlewares]
  [http.middlewares.redirect-to-https.redirectScheme]
    scheme = "https"
    permanent = true